queries:

  objects:
    file: "./objects.sparql"
    columns:
      - conceptUri 
  aspects:
    file: "./aspect.sparql"
    columns:
      - conceptUri 
      - aspectUri
    ignored_columns:
      - conceptName

include_unchanged: False

endpoints:
  old:
    url: https://hub.laces.tech/semmtech/cases/example-publication-for-changelog-tool/versions/1/sparql?
#    username: YOUR_USERNAME_                                     # Prefer to use the Command-Line-Interface (CLI) to enter your username and password
#    password: YOUR_APPROVED_APP_PASSWORD                         # Or set them in your environment (LDP_USERNAME, LDP_PASSWORD) (The same as stylesheet-composer)
    default_graph_uri: []                                         # This option is still available, if you need to use very specific passwords, or 1 of the endpoints has different passwords.
    named_graph_uri: []
    
  new: 
    url:   https://hub.laces.tech/semmtech/cases/example-publication-for-changelog-tool/versions/2/sparql?
#    username: YOUR_USERNAME_
#    password: YOUR_APPROVED_APP_PASSWORD
    default_graph_uri: []
    named_graph_uri: []

    
output_path: output_file.xlsx

