queries:
  Specifications General Info:
    file: "./EU-303VS2 - Requirements General Info.sparql"
    columns:
      - specUri
  Requirements Taxonomy:
    file: "./EU-303VS2 - Requirements Taxonomy.sparql"
    columns:
      - specUri
  Conceptual Specifications:
    file: "./EU-303VS2 - Conceptual Specifications.sparql"
    columns:
      - conceptualSpecUri
endpoints:
  old: 
    url: https://hub.laces.tech/tennet/gfo-nl/eu-303/private/live/tennet/library/eu-303-vs2/versions/v9_0/sparql?default-graph-uri=http://hub.laces.tech/tennet/gfo-nl/eu-303/private/live/tennet/library/eu-303-atl/versions/v7_0&default-graph-uri=https://hub.laces.tech/tennet/gfo-nl/eu-303/private/live/tennet/library/eu-303-dcc/versions/v6_1
    username: 9d8f4122-7435-464f-8be5-8ad1631dc5de
    password: CgYucApC4CUEzkoHA9iP
    default-graph-uri: []
    named-graph-uri: []
  new:
    url: https://hub.laces.tech/tennet/gfo-nl/eu-303/private/live/tennet/library/eu-303-vs2/versions/v10_0/sparql?default-graph-uri=http://hub.laces.tech/tennet/gfo-nl/eu-303/private/live/tennet/library/eu-303-atl/versions/v7_1&default-graph-uri=https://hub.laces.tech/tennet/gfo-nl/eu-303/private/live/tennet/library/eu-303-dcc/versions/v6_1
    username: 9d8f4122-7435-464f-8be5-8ad1631dc5de
    password: CgYucApC4CUEzkoHA9iP
    default-graph-uri: []
    named-graph-uri: []    
output_path: VS2 v9_0 to v10_0 changelog.xlsx
