queries:

  objects:
    file: "../queries/objects.sparql"
    columns:
      - conceptUri 

include_unchanged: True

endpoints:
  old:
    url: https://hub.laces.tech/semmtech/consultancy/trainings/sparql/streamlit-changelog-/versions/1/sparql?
    username: 48df738b-66fa-4b83-829e-5b5e21d28b55                                     # Prefer to use the Command-Line-Interface (CLI) to enter your username and password
    password: hanji95!                         # Or set them in your environment (LDP_USERNAME, LDP_PASSWORD) (The same as stylesheet-composer)
    default_graph_uri: []                                         # This option is still available, if you need to use very specific passwords, or 1 of the endpoints has different passwords.
    named_graph_uri: []
    
  new: 
    url: https://hub.laces.tech/semmtech/consultancy/trainings/sparql/streamlit-changelog-/versions/2/sparql?
    username: 48df738b-66fa-4b83-829e-5b5e21d28b55                                     # Prefer to use the Command-Line-Interface (CLI) to enter your username and password
    password: hanji95!                         # Or set them in your environm
    default_graph_uri: []
    named_graph_uri: []

output_path: output_file.xlsx